# Generated by Django 3.2.9 on 2021-11-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobId', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('moveDate', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('availableDelivery', models.CharField(max_length=200)),
                ('movingFrom', models.CharField(max_length=200)),
                ('movingTo', models.CharField(max_length=200)),
                ('Lbs', models.CharField(max_length=200)),
                ('miles', models.CharField(max_length=200)),
                ('estimate', models.CharField(max_length=200)),
            ],
        ),
    ]
